import { useRouter } from "next/router";
import Head from "next/head";

const TutorialsArticle = () => {
  const router = useRouter();

  console.log(router.pathname);
  console.log(router.query.guideID);

  //send a request to some backend server
  return (
    <>
      <Head>
        <title>Thema von der Übersicht</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>TutorialsArticle</h1>
      </main>
    </>
  );
};

export default TutorialsArticle;
