import Head from "next/head";
import OverviewComponent from "@/components/overview";

const Tutorials = () => {
  //send a request to some backend server

  return (
    <>
      <Head>
        <title>Thema von der Übersicht</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <OverviewComponent type={"first"} />
      </main>
    </>
  );
};

export default Tutorials;
