import { useRouter } from "next/router";
import Head from "next/head";
import DetailviewComponent from "@/components/detailview";

const BlogDetailview = () => {
  const router = useRouter();

  console.log(router.pathname);
  console.log(router.query.postID);

  const id = router.query.postID ? router.query.postID.toString() : "";

  //send a request to some backend server

  return (
    <>
      <Head>
        <title>Thema von der Übersicht</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="page-wrapper-detail">
        <DetailviewComponent id={id}></DetailviewComponent>
      </main>
    </>
  );
};

export default BlogDetailview;
