import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import bird from "@/public/images/bird1.jpg";
import bird1 from "@/public/images/bird2.jpg";

const Themes = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="page-wrapper">
        <div className="themes">
          <h1>Themen</h1>
          <div className="themes-wrapper">
            <div className="themes-list">
              <div className="theme-box-wrapper">
                <div className="basic-container theme-box">
                  <Link href="/themen/thema">
                    <div className="img-wrapper">
                      <Image className="basic-image" alt="" src={bird} />
                    </div>
                  </Link>
                  <div className="theme-info">
                    <h2 className="title-small">
                      <Link href="">Züchten</Link>
                    </h2>
                    <p className="post-count">7 Artikel</p>
                  </div>
                </div>
              </div>
              <div className="theme-box-wrapper">
                <div className="basic-container theme-box">
                  <Link href="/themen/thema">
                    <div className="img-wrapper">
                      <Image className="basic-image" alt="" src={bird1} />
                    </div>
                  </Link>
                  <div className="theme-info">
                    <h2 className="title-small">
                      <Link href="">Züchten</Link>
                    </h2>
                    <p className="post-count">7 Artikel</p>
                  </div>
                </div>
              </div>
              <div className="theme-box-wrapper">
                <div className="basic-container theme-box">
                  <Link href="/themen/thema">
                    <div className="img-wrapper">
                      <Image className="basic-image" alt="" src={bird1} />
                    </div>
                  </Link>
                  <div className="theme-info">
                    <h2 className="title-small">
                      <Link href="">Züchten</Link>
                    </h2>
                    <p className="post-count">7 Artikel</p>
                  </div>
                </div>
              </div>

              <div className="theme-box-wrapper">
                <div className="basic-container theme-box">
                  <Link href="/themen/thema">
                    <div className="img-wrapper">
                      <Image className="basic-image" alt="" src={bird1} />
                    </div>
                  </Link>
                  <div className="theme-info">
                    <h2 className="title-small">
                      <Link href="">Züchten</Link>
                    </h2>
                    <p className="post-count">7 Artikel</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div></div>
        </div>
      </main>
    </>
  );
};

export default Themes;
