import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import bird from "@/public/images/bird1.jpg";

const Authors = () => {
  return (
    <>
      <Head>
        <title>Thema von der Übersicht</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="page-wrapper">
        <div className="authors">
          <h1>Autoren</h1>
          <div className="themes-wrapper">
            <div className="themes-list">
              <div className="theme-box-wrapper">
                <div className="basic-container theme-box">
                  <Link href="#">
                    <div className="img-wrapper">
                      <Image className="static-image" alt="" src={bird} />
                    </div>
                  </Link>
                  <div className="theme-info">
                    <h2 className="title-small">
                      <Link href="">Max Budziat</Link>
                    </h2>
                    <p className="description">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, nisi ipsa, minima iusto ipsam magni itaque fugit inventore impedit, eos libero culpa? Molestias quo illum commodi ea delectus, at ipsa.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Authors;
